namespace MetaverseConcert
{
    partial class fBookedResult
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.label8 = new System.Windows.Forms.Label();
            this.label9 = new System.Windows.Forms.Label();
            this.label10 = new System.Windows.Forms.Label();
            this.label11 = new System.Windows.Forms.Label();
            this.button1 = new System.Windows.Forms.Button();
            this.txtUserType = new System.Windows.Forms.TextBox();
            this.txtAqty = new System.Windows.Forms.TextBox();
            this.txtBQty = new System.Windows.Forms.TextBox();
            this.txtAprice = new System.Windows.Forms.TextBox();
            this.txtBPrice = new System.Windows.Forms.TextBox();
            this.txtTotal = new System.Windows.Forms.TextBox();
            this.txtPayment = new System.Windows.Forms.TextBox();
            this.txtName = new System.Windows.Forms.TextBox();
            this.txtCardno = new System.Windows.Forms.TextBox();
            this.txtExpire = new System.Windows.Forms.TextBox();
            this.txtCVV = new System.Windows.Forms.TextBox();
            this.SuspendLayout();
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(265, 87);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(141, 23);
            this.label1.TabIndex = 0;
            this.label1.Text = "ประเภทผู้ร่วมงาน";
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(265, 140);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(69, 23);
            this.label2.TabIndex = 1;
            this.label2.Text = "A1-A10";
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(265, 184);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(69, 23);
            this.label3.TabIndex = 2;
            this.label3.Text = "B1-B10";
            this.label4.AutoSize = true;
            this.label4.Location = new System.Drawing.Point(553, 140);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(76, 23);
            this.label4.TabIndex = 3;
            this.label4.Text = "ราคารวม"; 
            this.label5.AutoSize = true;
            this.label5.Location = new System.Drawing.Point(553, 194);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(76, 23);
            this.label5.TabIndex = 4;
            this.label5.Text = "ราคารวม";
            this.label6.AutoSize = true;
            this.label6.Location = new System.Drawing.Point(265, 256);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(76, 23);
            this.label6.TabIndex = 5;
            this.label6.Text = "ราคารวม";
            this.label7.AutoSize = true;
            this.label7.Location = new System.Drawing.Point(265, 322);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(164, 23);
            this.label7.TabIndex = 6;
            this.label7.Text = "ประเภทการชำระเงิน";
            this.label7.Click += new System.EventHandler(this.label7_Click); 
            this.label8.AutoSize = true;
            this.label8.Location = new System.Drawing.Point(275, 375);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(33, 23);
            this.label8.TabIndex = 7;
            this.label8.Text = "ชื่่อ";
            this.label9.AutoSize = true;
            this.label9.Location = new System.Drawing.Point(275, 429);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(116, 23);
            this.label9.TabIndex = 8;
            this.label9.Text = "หมายเลขบัตร"; 
            this.label10.AutoSize = true;
            this.label10.Location = new System.Drawing.Point(275, 478);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(112, 23);
            this.label10.TabIndex = 9;
            this.label10.Text = "วันที่หมดอายุ";
            this.label10.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.label11.AutoSize = true;
            this.label11.Location = new System.Drawing.Point(275, 534);
            this.label11.Name = "label11";
            this.label11.Size = new System.Drawing.Size(43, 23);
            this.label11.TabIndex = 10;
            this.label11.Text = "CVV"; 
            this.button1.Location = new System.Drawing.Point(1122, 657);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(119, 48);
            this.button1.TabIndex = 11;
            this.button1.Text = "ปิด";
            this.button1.UseVisualStyleBackColor = true;
            this.button1.Click += new System.EventHandler(this.button1_Click);
            this.txtUserType.Location = new System.Drawing.Point(425, 87);
            this.txtUserType.Name = "txtUserType";
            this.txtUserType.ReadOnly = true;
            this.txtUserType.Size = new System.Drawing.Size(144, 30);
            this.txtUserType.TabIndex = 12; 
            this.txtAqty.Location = new System.Drawing.Point(347, 137);
            this.txtAqty.Name = "txtAqty";
            this.txtAqty.ReadOnly = true;
            this.txtAqty.Size = new System.Drawing.Size(100, 30);
            this.txtAqty.TabIndex = 13; 
            this.txtBQty.Location = new System.Drawing.Point(347, 187);
            this.txtBQty.Name = "txtBQty";
            this.txtBQty.ReadOnly = true;
            this.txtBQty.Size = new System.Drawing.Size(100, 30);
            this.txtBQty.TabIndex = 14;
            this.txtAprice.Location = new System.Drawing.Point(672, 137);
            this.txtAprice.Name = "txtAprice";
            this.txtAprice.ReadOnly = true;
            this.txtAprice.Size = new System.Drawing.Size(100, 30);
            this.txtAprice.TabIndex = 15;
            this.txtBPrice.Location = new System.Drawing.Point(672, 191);
            this.txtBPrice.Name = "txtBPrice";
            this.txtBPrice.ReadOnly = true;
            this.txtBPrice.Size = new System.Drawing.Size(100, 30);
            this.txtBPrice.TabIndex = 16;
            this.txtTotal.Location = new System.Drawing.Point(347, 249);
            this.txtTotal.Name = "txtTotal";
            this.txtTotal.ReadOnly = true;
            this.txtTotal.Size = new System.Drawing.Size(100, 30);
            this.txtTotal.TabIndex = 17;
            this.txtPayment.Location = new System.Drawing.Point(435, 322);
            this.txtPayment.Name = "txtPayment";
            this.txtPayment.ReadOnly = true;
            this.txtPayment.Size = new System.Drawing.Size(174, 30);
            this.txtPayment.TabIndex = 18; 
            this.txtName.Location = new System.Drawing.Point(435, 372);
            this.txtName.Name = "txtName";
            this.txtName.ReadOnly = true;
            this.txtName.Size = new System.Drawing.Size(174, 30);
            this.txtName.TabIndex = 19; 
            this.txtCardno.Location = new System.Drawing.Point(435, 422);
            this.txtCardno.Name = "txtCardno";
            this.txtCardno.ReadOnly = true;
            this.txtCardno.Size = new System.Drawing.Size(174, 30);
            this.txtCardno.TabIndex = 20; 
            this.txtExpire.Location = new System.Drawing.Point(435, 478);
            this.txtExpire.Name = "txtExpire";
            this.txtExpire.ReadOnly = true;
            this.txtExpire.Size = new System.Drawing.Size(174, 30);
            this.txtExpire.TabIndex = 21;
            this.txtExpire.TextChanged += new System.EventHandler(this.textBox10_TextChanged);
            this.txtCVV.Location = new System.Drawing.Point(435, 531);
            this.txtCVV.Name = "txtCVV";
            this.txtCVV.ReadOnly = true;
            this.txtCVV.Size = new System.Drawing.Size(174, 30);
            this.txtCVV.TabIndex = 22; 
            this.AutoScaleDimensions = new System.Drawing.SizeF(10F, 23F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1333, 796);
            this.Controls.Add(this.txtCVV);
            this.Controls.Add(this.txtExpire);
            this.Controls.Add(this.txtCardno);
            this.Controls.Add(this.txtName);
            this.Controls.Add(this.txtPayment);
            this.Controls.Add(this.txtTotal);
            this.Controls.Add(this.txtBPrice);
            this.Controls.Add(this.txtAprice);
            this.Controls.Add(this.txtBQty);
            this.Controls.Add(this.txtAqty);
            this.Controls.Add(this.txtUserType);
            this.Controls.Add(this.button1);
            this.Controls.Add(this.label11);
            this.Controls.Add(this.label10);
            this.Controls.Add(this.label9);
            this.Controls.Add(this.label8);
            this.Controls.Add(this.label7);
            this.Controls.Add(this.label6);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.label1);
            this.Font = new System.Drawing.Font("Tahoma", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Margin = new System.Windows.Forms.Padding(5);
            this.Name = "fBookedResult";
            this.Text = "Form7";
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.Label label10;
        private System.Windows.Forms.Label label11;
        private System.Windows.Forms.Button button1;
        private System.Windows.Forms.TextBox txtUserType;
        private System.Windows.Forms.TextBox txtAqty;
        private System.Windows.Forms.TextBox txtBQty;
        private System.Windows.Forms.TextBox txtAprice;
        private System.Windows.Forms.TextBox txtBPrice;
        private System.Windows.Forms.TextBox txtTotal;
        private System.Windows.Forms.TextBox txtPayment;
        private System.Windows.Forms.TextBox txtName;
        private System.Windows.Forms.TextBox txtCardno;
        private System.Windows.Forms.TextBox txtExpire;
        private System.Windows.Forms.TextBox txtCVV;
    }
}