namespace MetaverseConcert
{
    partial class fRegister
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            this.label1 = new System.Windows.Forms.Label();
            this.cboTitle = new System.Windows.Forms.ComboBox();
            this.label2 = new System.Windows.Forms.Label();
            this.txtFName = new System.Windows.Forms.TextBox();
            this.label3 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.txtLname = new System.Windows.Forms.TextBox();
            this.txtAge = new System.Windows.Forms.TextBox();
            this.txtEmail = new System.Windows.Forms.TextBox();
            this.txtPassword = new System.Windows.Forms.TextBox();
            this.rdoAdult = new System.Windows.Forms.RadioButton();
            this.rdoStudent = new System.Windows.Forms.RadioButton();
            this.txtStudentId = new System.Windows.Forms.TextBox();
            this.txtEmail1 = new System.Windows.Forms.TextBox();
            this.txtAge1 = new System.Windows.Forms.TextBox();
            this.txtLname1 = new System.Windows.Forms.TextBox();
            this.label7 = new System.Windows.Forms.Label();
            this.label8 = new System.Windows.Forms.Label();
            this.label9 = new System.Windows.Forms.Label();
            this.label10 = new System.Windows.Forms.Label();
            this.txtFname1 = new System.Windows.Forms.TextBox();
            this.label11 = new System.Windows.Forms.Label();
            this.cboTitle1 = new System.Windows.Forms.ComboBox();
            this.label12 = new System.Windows.Forms.Label();
            this.btnSave = new System.Windows.Forms.Button();
            this.txtCpassword = new System.Windows.Forms.TextBox();
            this.label13 = new System.Windows.Forms.Label();
            this.txtCpassword1 = new System.Windows.Forms.TextBox();
            this.label14 = new System.Windows.Forms.Label();
            this.txtPassword1 = new System.Windows.Forms.TextBox();
            this.label15 = new System.Windows.Forms.Label();
            this.SuspendLayout();
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(331, 98);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(86, 23);
            this.label1.TabIndex = 0;
            this.label1.Text = "คำนำหน้า";
            this.cboTitle.FormattingEnabled = true;
            this.cboTitle.Items.AddRange(new object[] {
            "นาย",
            "นาง",
            "นางสาว"});
            this.cboTitle.Location = new System.Drawing.Point(460, 90);
            this.cboTitle.Name = "cboTitle";
            this.cboTitle.Size = new System.Drawing.Size(121, 31);
            this.cboTitle.TabIndex = 1;
            this.cboTitle.SelectedIndexChanged += new System.EventHandler(this.comboBox1_SelectedIndexChanged);
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(331, 159);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(33, 23);
            this.label2.TabIndex = 2;
            this.label2.Text = "ชื่อ";
            this.txtFName.Location = new System.Drawing.Point(459, 156);
            this.txtFName.Name = "txtFName";
            this.txtFName.Size = new System.Drawing.Size(150, 30);
            this.txtFName.TabIndex = 3;
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(331, 217);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(45, 23);
            this.label3.TabIndex = 4;
            this.label3.Text = "สกุล";
            this.label4.AutoSize = true;
            this.label4.Location = new System.Drawing.Point(331, 266);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(41, 23);
            this.label4.TabIndex = 5;
            this.label4.Text = "อายุ";
            this.label5.AutoSize = true;
            this.label5.Location = new System.Drawing.Point(331, 319);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(50, 23);
            this.label5.TabIndex = 6;
            this.label5.Text = "อีเมล์"; 
            this.label6.AutoSize = true;
            this.label6.Location = new System.Drawing.Point(331, 363);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(76, 23);
            this.label6.TabIndex = 7;
            this.label6.Text = "รหัสผ่าน"; 
            this.txtLname.Location = new System.Drawing.Point(460, 213);
            this.txtLname.Name = "txtLname";
            this.txtLname.Size = new System.Drawing.Size(149, 30);
            this.txtLname.TabIndex = 8;
            this.txtAge.Location = new System.Drawing.Point(459, 263);
            this.txtAge.Name = "txtAge";
            this.txtAge.Size = new System.Drawing.Size(100, 30);
            this.txtAge.TabIndex = 9;
            this.txtEmail.Location = new System.Drawing.Point(460, 312);
            this.txtEmail.Name = "txtEmail";
            this.txtEmail.Size = new System.Drawing.Size(149, 30);
            this.txtEmail.TabIndex = 10; 
            this.txtPassword.Location = new System.Drawing.Point(460, 359);
            this.txtPassword.Name = "txtPassword";
            this.txtPassword.Size = new System.Drawing.Size(100, 30);
            this.txtPassword.TabIndex = 11;
            this.rdoAdult.AutoSize = true;
            this.rdoAdult.Location = new System.Drawing.Point(335, 50);
            this.rdoAdult.Name = "rdoAdult";
            this.rdoAdult.Size = new System.Drawing.Size(121, 27);
            this.rdoAdult.TabIndex = 12;
            this.rdoAdult.TabStop = true;
            this.rdoAdult.Text = "บุคคลทั่วไป";
            this.rdoAdult.UseVisualStyleBackColor = true;
            this.rdoAdult.CheckedChanged += new System.EventHandler(this.radioButton1_CheckedChanged);
            this.rdoStudent.AutoSize = true;
            this.rdoStudent.Location = new System.Drawing.Point(669, 50);
            this.rdoStudent.Name = "rdoStudent";
            this.rdoStudent.Size = new System.Drawing.Size(88, 27);
            this.rdoStudent.TabIndex = 13;
            this.rdoStudent.TabStop = true;
            this.rdoStudent.Text = "นักเรียน";
            this.rdoStudent.UseVisualStyleBackColor = true;
            this.rdoStudent.CheckedChanged += new System.EventHandler(this.radioButton2_CheckedChanged);
            this.txtStudentId.Location = new System.Drawing.Point(802, 363);
            this.txtStudentId.Name = "txtStudentId";
            this.txtStudentId.Size = new System.Drawing.Size(163, 30);
            this.txtStudentId.TabIndex = 25;
            this.txtEmail1.Location = new System.Drawing.Point(802, 312);
            this.txtEmail1.Name = "txtEmail1";
            this.txtEmail1.Size = new System.Drawing.Size(163, 30);
            this.txtEmail1.TabIndex = 24;
            this.txtAge1.Location = new System.Drawing.Point(802, 266);
            this.txtAge1.Name = "txtAge1";
            this.txtAge1.Size = new System.Drawing.Size(100, 30);
            this.txtAge1.TabIndex = 23;
            this.txtLname1.Location = new System.Drawing.Point(802, 210);
            this.txtLname1.Name = "txtLname1";
            this.txtLname1.Size = new System.Drawing.Size(163, 30);
            this.txtLname1.TabIndex = 22;
            this.label7.AutoSize = true;
            this.label7.Location = new System.Drawing.Point(673, 363);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(103, 23);
            this.label7.TabIndex = 21;
            this.label7.Text = "รหัสนักเรียน";
            this.label8.AutoSize = true;
            this.label8.Location = new System.Drawing.Point(673, 319);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(50, 23);
            this.label8.TabIndex = 20;
            this.label8.Text = "อีเมล์";
            this.label9.AutoSize = true;
            this.label9.Location = new System.Drawing.Point(673, 266);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(41, 23);
            this.label9.TabIndex = 19;
            this.label9.Text = "อายุ";
            this.label10.AutoSize = true;
            this.label10.Location = new System.Drawing.Point(673, 217);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(45, 23);
            this.label10.TabIndex = 18;
            this.label10.Text = "สกุล";
            this.txtFname1.Location = new System.Drawing.Point(802, 152);
            this.txtFname1.Name = "txtFname1";
            this.txtFname1.Size = new System.Drawing.Size(163, 30);
            this.txtFname1.TabIndex = 17;
            this.label11.AutoSize = true;
            this.label11.Location = new System.Drawing.Point(673, 159);
            this.label11.Name = "label11";
            this.label11.Size = new System.Drawing.Size(33, 23);
            this.label11.TabIndex = 16;
            this.label11.Text = "ชื่อ";
            this.cboTitle1.FormattingEnabled = true;
            this.cboTitle1.Items.AddRange(new object[] {
            "นาย",
            "นาง",
            "นางสาว"});
            this.cboTitle1.Location = new System.Drawing.Point(802, 90);
            this.cboTitle1.Name = "cboTitle1";
            this.cboTitle1.Size = new System.Drawing.Size(121, 31);
            this.cboTitle1.TabIndex = 15;
            this.label12.AutoSize = true;
            this.label12.Location = new System.Drawing.Point(673, 98);
            this.label12.Name = "label12";
            this.label12.Size = new System.Drawing.Size(86, 23);
            this.label12.TabIndex = 14;
            this.label12.Text = "คำนำหน้า";
            this.btnSave.Location = new System.Drawing.Point(591, 591);
            this.btnSave.Name = "btnSave";
            this.btnSave.Size = new System.Drawing.Size(144, 69);
            this.btnSave.TabIndex = 26;
            this.btnSave.Text = "บันทึก";
            this.btnSave.UseVisualStyleBackColor = true;
            this.btnSave.Click += new System.EventHandler(this.btnSave_Click); 
            this.txtCpassword.Location = new System.Drawing.Point(459, 420);
            this.txtCpassword.Name = "txtCpassword";
            this.txtCpassword.Size = new System.Drawing.Size(100, 30);
            this.txtCpassword.TabIndex = 29;
            this.label13.AutoSize = true;
            this.label13.Location = new System.Drawing.Point(331, 423);
            this.label13.Name = "label13";
            this.label13.Size = new System.Drawing.Size(122, 23);
            this.label13.TabIndex = 28;
            this.label13.Text = "ยืนยันรหัสผ่าน"; 
            this.txtCpassword1.Location = new System.Drawing.Point(801, 480);
            this.txtCpassword1.Name = "txtCpassword1";
            this.txtCpassword1.Size = new System.Drawing.Size(100, 30);
            this.txtCpassword1.TabIndex = 33;
            this.label14.AutoSize = true;
            this.label14.Location = new System.Drawing.Point(673, 483);
            this.label14.Name = "label14";
            this.label14.Size = new System.Drawing.Size(122, 23);
            this.label14.TabIndex = 32;
            this.label14.Text = "ยืนยันรหัสผ่าน"; 
            this.txtPassword1.Location = new System.Drawing.Point(802, 419);
            this.txtPassword1.Name = "txtPassword1";
            this.txtPassword1.Size = new System.Drawing.Size(100, 30);
            this.txtPassword1.TabIndex = 31;
            this.label15.AutoSize = true;
            this.label15.Location = new System.Drawing.Point(673, 423);
            this.label15.Name = "label15";
            this.label15.Size = new System.Drawing.Size(76, 23);
            this.label15.TabIndex = 30;
            this.label15.Text = "รหัสผ่าน";
            this.AutoScaleDimensions = new System.Drawing.SizeF(10F, 23F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1333, 796);
            this.Controls.Add(this.txtCpassword1);
            this.Controls.Add(this.label14);
            this.Controls.Add(this.txtPassword1);
            this.Controls.Add(this.label15);
            this.Controls.Add(this.txtCpassword);
            this.Controls.Add(this.label13);
            this.Controls.Add(this.btnSave);
            this.Controls.Add(this.txtStudentId);
            this.Controls.Add(this.txtEmail1);
            this.Controls.Add(this.txtAge1);
            this.Controls.Add(this.txtLname1);
            this.Controls.Add(this.label7);
            this.Controls.Add(this.label8);
            this.Controls.Add(this.label9);
            this.Controls.Add(this.label10);
            this.Controls.Add(this.txtFname1);
            this.Controls.Add(this.label11);
            this.Controls.Add(this.cboTitle1);
            this.Controls.Add(this.label12);
            this.Controls.Add(this.rdoStudent);
            this.Controls.Add(this.rdoAdult);
            this.Controls.Add(this.txtPassword);
            this.Controls.Add(this.txtEmail);
            this.Controls.Add(this.txtAge);
            this.Controls.Add(this.txtLname);
            this.Controls.Add(this.label6);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.txtFName);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.cboTitle);
            this.Controls.Add(this.label1);
            this.Font = new System.Drawing.Font("Tahoma", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Margin = new System.Windows.Forms.Padding(5);
            this.Name = "fRegister";
            this.Text = "Form2";
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.ComboBox cboTitle;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.TextBox txtFName;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.TextBox txtLname;
        private System.Windows.Forms.TextBox txtAge;
        private System.Windows.Forms.TextBox txtEmail;
        private System.Windows.Forms.TextBox txtPassword;
        private System.Windows.Forms.RadioButton rdoAdult;
        private System.Windows.Forms.RadioButton rdoStudent;
        private System.Windows.Forms.TextBox txtStudentId;
        private System.Windows.Forms.TextBox txtEmail1;
        private System.Windows.Forms.TextBox txtAge1;
        private System.Windows.Forms.TextBox txtLname1;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.Label label10;
        private System.Windows.Forms.TextBox txtFname1;
        private System.Windows.Forms.Label label11;
        private System.Windows.Forms.ComboBox cboTitle1;
        private System.Windows.Forms.Label label12;
        private System.Windows.Forms.Button btnSave;
        private System.Windows.Forms.TextBox txtCpassword;
        private System.Windows.Forms.Label label13;
        private System.Windows.Forms.TextBox txtCpassword1;
        private System.Windows.Forms.Label label14;
        private System.Windows.Forms.TextBox txtPassword1;
        private System.Windows.Forms.Label label15;
    }
}